spring:
  application:
    name: putevodika-backend

  datasource:
    url: jdbc:postgresql://localhost:5433/putevodika
    username: putevodika
    password: putevodika

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  http:
    clients:
      connect-timeout: 2s
      read-timeout: 5s

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

app:
  security:
    jwt:
      issuer: putevodika-backend
      access-token-ttl: PT30M
      secret: ${JWT_SECRET}
  osrm:
    base-url: ${OSRM_BASE_URL:http://localhost:5000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

  api-docs:
    path: /v3/api-docs