INSERT INTO category (
    code,
    name,
    active,
    preference_selectable
)
VALUES
    ('AEROSPACE', 'Аэрокосмическая тематика', TRUE, FALSE),
    ('AGRICULTURE', 'Сельское хозяйство', TRUE, FALSE),
    ('AIRCRAFT', 'Самолёт', TRUE, FALSE),
    ('ALPINE_HUT', 'Горный приют', TRUE, FALSE),
    ('AMUSEMENT_RIDE', 'Аттракцион', TRUE, FALSE),
    ('ANCHOR', 'Якорь', TRUE, FALSE),
    ('ANIMAL', 'Животные', TRUE, FALSE),
    ('ANIME', 'Аниме', TRUE, FALSE),
    ('ANTIQUES', 'Антиквариат', TRUE, FALSE),
    ('AQUARIUM', 'Океанариум', TRUE, FALSE),
    ('ARCHAEOLOGICAL', 'Археология', TRUE, FALSE),
    ('ARCHAEOLOGICAL_SITE', 'Археологический объект', TRUE, FALSE),
    ('ARCHITECTURE', 'Архитектура', TRUE, FALSE),
    ('ARMY', 'Армия', TRUE, FALSE),
    ('ART', 'Искусство', TRUE, FALSE),
    ('ARTS_CENTRE', 'Центр искусств', TRUE, FALSE),
    ('ARTWORK', 'Произведение искусства', TRUE, FALSE),
    ('ATTRACTION', 'Достопримечательность', TRUE, FALSE),
    ('BAR', 'Бар', TRUE, FALSE),
    ('BARE_ROCK', 'Скальный выход', TRUE, FALSE),
    ('BATTLEFIELD', 'Поле боя', TRUE, FALSE),
    ('BAY', 'Залив', TRUE, FALSE),
    ('BEACH', 'Пляж', TRUE, FALSE),
    ('BICYCLE', 'Велосипедная тематика', TRUE, FALSE),
    ('BIG_WHEEL', 'Колесо обозрения', TRUE, FALSE),
    ('BOAT_RIDE', 'Водный аттракцион', TRUE, FALSE),
    ('BOOKS', 'Книги', TRUE, FALSE),
    ('BORDER_GUARD', 'Пограничная служба', TRUE, FALSE),
    ('BRIDGE', 'Мост', TRUE, FALSE),
    ('BUDDHIST', 'Буддизм', TRUE, FALSE),
    ('BUMPER_CAR', 'Автодром', TRUE, FALSE),
    ('BUNKER', 'Бункер', TRUE, FALSE),
    ('BUST', 'Бюст', TRUE, FALSE),
    ('CAFE', 'Кафе', TRUE, FALSE),
    ('CAMP_SITE', 'Кемпинг', TRUE, FALSE),
    ('CANNON', 'Пушка', TRUE, FALSE),
    ('CAROUSEL', 'Карусель', TRUE, FALSE),
    ('CASTLE', 'Замок', TRUE, FALSE),
    ('CATHEDRAL', 'Собор', TRUE, FALSE),
    ('CAVE_ENTRANCE', 'Вход в пещеру', TRUE, FALSE),
    ('CHAPEL', 'Часовня', TRUE, FALSE),
    ('CHARITY', 'Благотворительность', TRUE, FALSE),
    ('CHOCOLATE', 'Шоколад', TRUE, FALSE),
    ('CHRISTIAN', 'Христианство', TRUE, FALSE),
    ('CHURCH', 'Церковь', TRUE, FALSE),
    ('CITY_GATE', 'Городские ворота', TRUE, FALSE),
    ('CLIFF', 'Утёс', TRUE, FALSE),
    ('COFFEE', 'Кофе', TRUE, FALSE),
    ('COLLECTOR', 'Коллекционирование', TRUE, FALSE),
    ('COLLEGE', 'Колледж', TRUE, FALSE),
    ('COLUMN', 'Колонна', TRUE, FALSE),
    ('COMMUNICATIONS_TOWER', 'Башня связи', TRUE, FALSE),
    ('CROSS', 'Крест', TRUE, FALSE),
    ('DAM', 'Плотина', TRUE, FALSE),
    ('DEFENSIVE', 'Оборонительный объект', TRUE, FALSE),
    ('DROP_TOWER', 'Башня свободного падения', TRUE, FALSE),
    ('ETERNAL_FLAME', 'Вечный огонь', TRUE, FALSE),
    ('ETHNOGRAPHY', 'Этнография', TRUE, FALSE),
    ('FARMER', 'Фермерская тематика', TRUE, FALSE),
    ('FAST_FOOD', 'Фастфуд', TRUE, FALSE),
    ('FIREPLACE', 'Очаг', TRUE, FALSE),
    ('FOOD_COURT', 'Фуд-корт', TRUE, FALSE),
    ('FOOT', 'Пешеходный туризм', TRUE, FALSE),
    ('FORT', 'Форт', TRUE, FALSE),
    ('FORTIFICATION', 'Фортификация', TRUE, FALSE),
    ('FORTRESS', 'Крепость', TRUE, FALSE),
    ('FOUNTAIN', 'Фонтан', TRUE, FALSE),
    ('GALLERY', 'Галерея', TRUE, FALSE),
    ('GARDEN', 'Сад', TRUE, FALSE),
    ('GIFT', 'Сувениры и подарки', TRUE, FALSE),
    ('GLACIER', 'Ледник', TRUE, FALSE),
    ('GRAFFITI', 'Граффити', TRUE, FALSE),
    ('GRAVE', 'Могила', TRUE, FALSE),
    ('GUEST_HOUSE', 'Гостевой дом', TRUE, FALSE),
    ('HELICOPTER', 'Вертолёт', TRUE, FALSE),
    ('HERITAGE_SITE', 'Объект наследия', TRUE, FALSE),
    ('HERMITAGE', 'Скит', TRUE, FALSE),
    ('HIKING', 'Пеший туризм', TRUE, FALSE),
    ('HINDU', 'Индуизм', TRUE, FALSE),
    ('HISTORY', 'История', TRUE, FALSE),
    ('HONEY', 'Мёд', TRUE, FALSE),
    ('HOSTEL', 'Хостел', TRUE, FALSE),
    ('HOTEL', 'Отель', TRUE, FALSE),
    ('ICE_RINK', 'Каток', TRUE, FALSE),
    ('INSTALLATION', 'Инсталляция', TRUE, FALSE),
    ('INTERNET_CAFE', 'Интернет-кафе', TRUE, FALSE),
    ('JEWISH', 'Иудаизм', TRUE, FALSE),
    ('KIDDIE_RIDE', 'Детский аттракцион', TRUE, FALSE),
    ('KREMLIN', 'Кремль', TRUE, FALSE),
    ('LAKE', 'Озеро', TRUE, FALSE),
    ('LAND_ART', 'Лэнд-арт', TRUE, FALSE),
    ('LEATHER', 'Кожаные изделия', TRUE, FALSE),
    ('LIBRARY', 'Библиотека', TRUE, FALSE),
    ('LIGHTHOUSE', 'Маяк', TRUE, FALSE),
    ('LOCAL', 'Местная тематика', TRUE, FALSE),
    ('LOCAL_HISTORY', 'Краеведение', TRUE, FALSE),
    ('LOCALITY', 'Местность', TRUE, FALSE),
    ('LOCOMOTIVE', 'Локомотив', TRUE, FALSE),
    ('LOOKOUT_TOWER', 'Смотровая башня', TRUE, FALSE),
    ('MALL', 'Торговый центр', TRUE, FALSE),
    ('MANOR', 'Усадьба', TRUE, FALSE),
    ('MARITIME', 'Морская тематика', TRUE, FALSE),
    ('MAZE', 'Лабиринт', TRUE, FALSE),
    ('MEMORIAL', 'Мемориал', TRUE, FALSE),
    ('MILITARY', 'Военная тематика', TRUE, FALSE),
    ('MONASTERY', 'Монастырь', TRUE, FALSE),
    ('MONUMENT', 'Памятник', TRUE, FALSE),
    ('MOSAIC', 'Мозаика', TRUE, FALSE),
    ('MOSQUE', 'Мечеть', TRUE, FALSE),
    ('MOTEL', 'Мотель', TRUE, FALSE),
    ('MTB', 'Маунтинбайк', TRUE, FALSE),
    ('MURAL', 'Мурал', TRUE, FALSE),
    ('MUSEUM', 'Музей', TRUE, FALSE),
    ('MUSLIM', 'Ислам', TRUE, FALSE),
    ('NATIONAL_PARK', 'Национальный парк', TRUE, FALSE),
    ('NATURE', 'Природа', TRUE, FALSE),
    ('NATURE_RESERVE', 'Природный заповедник', TRUE, FALSE),
    ('NAVY', 'Военно-морская тематика', TRUE, FALSE),
    ('OBELISK', 'Обелиск', TRUE, FALSE),
    ('OPEN_AIR_MUSEUM', 'Музей под открытым небом', TRUE, FALSE),
    ('OPEN_AIR_THEATRE', 'Театр под открытым небом', TRUE, FALSE),
    ('ORTHODOX', 'Православие', TRUE, FALSE),
    ('PAINTING', 'Живопись', TRUE, FALSE),
    ('PALACE', 'Дворец', TRUE, FALSE),
    ('PARK', 'Парк', TRUE, FALSE),
    ('PEAK', 'Горная вершина', TRUE, FALSE),
    ('PICNIC_SITE', 'Место для пикника', TRUE, FALSE),
    ('PIER', 'Пирс', TRUE, FALSE),
    ('PIRATE_SHIP', 'Пиратский корабль', TRUE, FALSE),
    ('PLACE_OF_WORSHIP', 'Место богослужения', TRUE, FALSE),
    ('PLAQUE', 'Мемориальная доска', TRUE, FALSE),
    ('POND', 'Пруд', TRUE, FALSE),
    ('POTTERY', 'Керамика', TRUE, FALSE),
    ('PUB', 'Паб', TRUE, FALSE),
    ('RAILWAY', 'Железнодорожная тематика', TRUE, FALSE),
    ('RECREATION_GROUND', 'Зона отдыха', TRUE, FALSE),
    ('RELIEF', 'Рельеф', TRUE, FALSE),
    ('RELIGIOUS', 'Религиозный объект', TRUE, FALSE),
    ('RENTAL', 'Прокат', TRUE, FALSE),
    ('RESERVOIR', 'Водохранилище', TRUE, FALSE),
    ('RESTAURANT', 'Ресторан', TRUE, FALSE),
    ('RIDGE', 'Горный хребет', TRUE, FALSE),
    ('ROCK', 'Скала', TRUE, FALSE),
    ('ROLLER_COASTER', 'Американские горки', TRUE, FALSE),
    ('RUINS', 'Руины', TRUE, FALSE),
    ('SCULPTURE', 'Скульптура', TRUE, FALSE),
    ('SHINTO', 'Синтоизм', TRUE, FALSE),
    ('SHIP', 'Корабль', TRUE, FALSE),
    ('SKI', 'Лыжная тематика', TRUE, FALSE),
    ('SLIDE', 'Горка', TRUE, FALSE),
    ('SPACE_FORCE', 'Космические войска', TRUE, FALSE),
    ('SPRING', 'Родник', TRUE, FALSE),
    ('STATUE', 'Статуя', TRUE, FALSE),
    ('STELE', 'Стела', TRUE, FALSE),
    ('STONE', 'Камень', TRUE, FALSE),
    ('STREET_ART', 'Уличное искусство', TRUE, FALSE),
    ('STUPA', 'Ступа', TRUE, FALSE),
    ('SWING', 'Качели', TRUE, FALSE),
    ('SWING_CAROUSEL', 'Цепочная карусель', TRUE, FALSE),
    ('SYNAGOGUE', 'Синагога', TRUE, FALSE),
    ('TANK', 'Танк', TRUE, FALSE),
    ('TANK_TURRET', 'Танковая башня', TRUE, FALSE),
    ('TATTOO', 'Татуировка', TRUE, FALSE),
    ('TEA', 'Чай', TRUE, FALSE),
    ('TECHNICAL_MONUMENT', 'Технический памятник', TRUE, FALSE),
    ('TECHNOLOGY', 'Технологии', TRUE, FALSE),
    ('TEMPLE', 'Храм', TRUE, FALSE),
    ('THEATRE', 'Театр', TRUE, FALSE),
    ('THEME_PARK', 'Парк развлечений', TRUE, FALSE),
    ('TOMB', 'Гробница', TRUE, FALSE),
    ('TOWER', 'Башня', TRUE, FALSE),
    ('TOWNHALL', 'Ратуша', TRUE, FALSE),
    ('TRAIN', 'Поезд', TRUE, FALSE),
    ('TRAMPOLINE_PARK', 'Батутный парк', TRUE, FALSE),
    ('TRANSPORT', 'Транспорт', TRUE, FALSE),
    ('TRENCH', 'Траншея', TRUE, FALSE),
    ('UNIVERSITY', 'Университет', TRUE, FALSE),
    ('VALLEY', 'Долина', TRUE, FALSE),
    ('VEHICLE', 'Транспортное средство', TRUE, FALSE),
    ('VIEWPOINT', 'Смотровая площадка', TRUE, FALSE),
    ('WAR', 'Военная история', TRUE, FALSE),
    ('WAR_CEMETERY', 'Военное кладбище', TRUE, FALSE),
    ('WAR_MEMORIAL', 'Военный мемориал', TRUE, FALSE),
    ('WATER_PARK', 'Аквапарк', TRUE, FALSE),
    ('WATER_SLIDE', 'Водная горка', TRUE, FALSE),
    ('WATER_TANK', 'Резервуар для воды', TRUE, FALSE),
    ('WATER_TOWER', 'Водонапорная башня', TRUE, FALSE),
    ('WATER_WELL', 'Колодец', TRUE, FALSE),
    ('WATERFALL', 'Водопад', TRUE, FALSE),
    ('WAYSIDE_CROSS', 'Придорожный крест', TRUE, FALSE),
    ('WAYSIDE_SHRINE', 'Придорожная святыня', TRUE, FALSE),
    ('WILDERNESS_HUT', 'Лесной приют', TRUE, FALSE),
    ('WINE', 'Вино', TRUE, FALSE),
    ('ZOO', 'Зоопарк', TRUE, FALSE)

    ON CONFLICT (code)
DO UPDATE SET
    name = EXCLUDED.name,
           active = TRUE;