-- Административный аудит (без паролей, JWT и содержимого файлов).
CREATE TABLE admin_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT REFERENCES app_user(id) ON DELETE SET NULL,
    action VARCHAR(80) NOT NULL,
    subject_type VARCHAR(40) NOT NULL,
    subject_id VARCHAR(128),
    details VARCHAR(500),
    client_ip VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_admin_audit_created ON admin_audit_log (created_at DESC, id DESC);
CREATE INDEX idx_admin_audit_actor ON admin_audit_log (actor_user_id, created_at DESC);
CREATE INDEX idx_admin_audit_subject ON admin_audit_log (subject_type, subject_id);

-- История только файлового OSM-импорта, который проходит через TrackedPlaceFileImportService.
CREATE TABLE admin_import_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT REFERENCES app_user(id) ON DELETE SET NULL,
    file_name VARCHAR(255) NOT NULL,
    file_size_bytes BIGINT NOT NULL CHECK (file_size_bytes >= 0),
    status VARCHAR(32) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    total_count INTEGER NOT NULL DEFAULT 0,
    created_count INTEGER NOT NULL DEFAULT 0,
    updated_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    error_message TEXT
);
CREATE INDEX idx_admin_import_started ON admin_import_job (started_at DESC, id DESC);
CREATE INDEX idx_admin_import_status ON admin_import_job (status, started_at DESC);

-- Первые 200 ошибок импорта: неограниченный журнал ошибок для крупных файлов не создаём.
CREATE TABLE admin_import_job_failure (
    job_id BIGINT NOT NULL REFERENCES admin_import_job(id) ON DELETE CASCADE,
    item_order INTEGER NOT NULL,
    object_id VARCHAR(128) NOT NULL,
    error_text TEXT NOT NULL,
    PRIMARY KEY (job_id, item_order)
);
