CREATE TABLE category
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    VARCHAR(64)  NOT NULL UNIQUE,
    name    VARCHAR(128) NOT NULL,
    active  BOOLEAN      NOT NULL DEFAULT TRUE
);


CREATE TABLE place
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name        VARCHAR(255) NOT NULL,
    description TEXT,
    address     VARCHAR(500),

    location    geometry(Point, 4326) NOT NULL,

    source_type VARCHAR(32) NOT NULL,
    external_id VARCHAR(128),

    active      BOOLEAN NOT NULL DEFAULT TRUE,

    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_place_source_external
        UNIQUE (source_type, external_id)
);


CREATE TABLE place_category
(
    place_id    BIGINT NOT NULL,
    category_id BIGINT NOT NULL,

    PRIMARY KEY (place_id, category_id),

    CONSTRAINT fk_place_category_place
        FOREIGN KEY (place_id)
            REFERENCES place (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_place_category_category
        FOREIGN KEY (category_id)
            REFERENCES category (id)
);


CREATE INDEX idx_place_location
    ON place
    USING GIST (location);


CREATE INDEX idx_place_active
    ON place (active);


CREATE INDEX idx_place_category_category
    ON place_category (category_id);

INSERT INTO category (code, name)
VALUES
    ('MUSEUM', 'Музей'),
    ('MONUMENT', 'Памятник'),
    ('ARCHITECTURE', 'Архитектура'),
    ('NATURE', 'Природа'),
    ('PARK', 'Парк'),
    ('VIEWPOINT', 'Смотровая площадка'),
    ('RELIGIOUS', 'Религиозный объект'),
    ('CULTURE', 'Культура');