CREATE TABLE app_user
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    email         VARCHAR(320) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(100) NOT NULL,

    role          VARCHAR(32) NOT NULL DEFAULT 'USER',

    active        BOOLEAN NOT NULL DEFAULT TRUE,

    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE UNIQUE INDEX uq_app_user_email_lower
    ON app_user (LOWER(email));


CREATE INDEX idx_app_user_active
    ON app_user (active);


CREATE INDEX idx_app_user_role
    ON app_user (role);


CREATE TABLE user_preferred_category
(
    user_id     BIGINT NOT NULL,
    category_id BIGINT NOT NULL,

    PRIMARY KEY (user_id, category_id),

    CONSTRAINT fk_user_preferred_category_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_user_preferred_category_category
        FOREIGN KEY (category_id)
            REFERENCES category (id)
);