ALTER TABLE place
    ADD COLUMN visit_duration_minutes INTEGER,
    ADD COLUMN opening_hours VARCHAR(255);


ALTER TABLE place
    ADD CONSTRAINT ck_place_visit_duration
        CHECK (
            visit_duration_minutes IS NULL
                OR visit_duration_minutes BETWEEN 1 AND 1440
            );


CREATE TABLE feature
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    VARCHAR(64)  NOT NULL UNIQUE,
    name    VARCHAR(128) NOT NULL,
    active  BOOLEAN      NOT NULL DEFAULT TRUE
);


CREATE TABLE place_feature
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id   BIGINT   NOT NULL,
    feature_id BIGINT   NOT NULL,
    value      SMALLINT NOT NULL,

    CONSTRAINT uq_place_feature
        UNIQUE (place_id, feature_id),

    CONSTRAINT ck_place_feature_value
        CHECK (value BETWEEN 0 AND 5),

    CONSTRAINT fk_place_feature_place
        FOREIGN KEY (place_id)
            REFERENCES place (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_place_feature_feature
        FOREIGN KEY (feature_id)
            REFERENCES feature (id)
);


CREATE INDEX idx_place_feature_feature
    ON place_feature (feature_id);


CREATE TABLE user_feature_preference
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT   NOT NULL,
    feature_id BIGINT   NOT NULL,
    weight     SMALLINT NOT NULL,

    CONSTRAINT uq_user_feature_preference
        UNIQUE (user_id, feature_id),

    CONSTRAINT ck_user_feature_preference_weight
        CHECK (weight BETWEEN 0 AND 5),

    CONSTRAINT fk_user_feature_preference_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_user_feature_preference_feature
        FOREIGN KEY (feature_id)
            REFERENCES feature (id)
);


CREATE INDEX idx_user_feature_preference_feature
    ON user_feature_preference (feature_id);


INSERT INTO feature (code, name)
VALUES
    ('MILITARY', 'Военная тематика'),
    ('RELIGIOUS', 'Религиозная тематика'),
    ('ARCHITECTURE', 'Архитектурная ценность'),
    ('INTERACTIVE', 'Интерактивность'),
    ('TRANSPORT', 'Транспортная тематика');