CREATE TABLE saved_route
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    start_point  geometry(Point, 4326) NOT NULL,
    finish_point geometry(Point, 4326) NOT NULL,

    walking_distance_meters  INTEGER,
    walking_duration_seconds INTEGER,
    total_duration_minutes   INTEGER,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_saved_route_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (id)
            ON DELETE CASCADE,

    CONSTRAINT ck_saved_route_distance
        CHECK (
            walking_distance_meters IS NULL
                OR walking_distance_meters >= 0
            ),

    CONSTRAINT ck_saved_route_walking_duration
        CHECK (
            walking_duration_seconds IS NULL
                OR walking_duration_seconds >= 0
            ),

    CONSTRAINT ck_saved_route_total_duration
        CHECK (
            total_duration_minutes IS NULL
                OR total_duration_minutes >= 0
            )
);


CREATE INDEX idx_saved_route_user_created
    ON saved_route (user_id, created_at DESC);


CREATE TABLE route_place
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    route_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,

    position INTEGER NOT NULL,

    CONSTRAINT fk_route_place_route
        FOREIGN KEY (route_id)
            REFERENCES saved_route (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_route_place_place
        FOREIGN KEY (place_id)
            REFERENCES place (id),

    CONSTRAINT uq_route_place_position
        UNIQUE (route_id, position),

    CONSTRAINT uq_route_place_place
        UNIQUE (route_id, place_id),

    CONSTRAINT ck_route_place_position
        CHECK (position > 0)
);


CREATE INDEX idx_route_place_route_position
    ON route_place (route_id, position);


CREATE INDEX idx_route_place_place
    ON route_place (place_id);


CREATE TABLE route_rating
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    route_id BIGINT NOT NULL,
    user_id  BIGINT NOT NULL,

    value SMALLINT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_route_rating_route
        FOREIGN KEY (route_id)
            REFERENCES saved_route (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_route_rating_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (id)
            ON DELETE CASCADE,

    CONSTRAINT uq_route_rating_user
        UNIQUE (route_id, user_id),

    CONSTRAINT ck_route_rating_value
        CHECK (value BETWEEN 1 AND 5)
);


CREATE INDEX idx_route_rating_route
    ON route_rating (route_id);