CREATE TABLE refresh_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id     BIGINT NOT NULL,
    token_hash  VARCHAR(64) NOT NULL,

    created_at  TIMESTAMPTZ NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked_at  TIMESTAMPTZ,

    CONSTRAINT fk_refresh_token_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (id)
            ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_refresh_token_hash
    ON refresh_token (token_hash);

CREATE INDEX idx_refresh_token_user
    ON refresh_token (user_id);

CREATE INDEX idx_refresh_token_expires
    ON refresh_token (expires_at);